@file:Suppress("unused", "FunctionName")
package com.badlogic.gdx.physics.box2d

import com.badlogic.gdx.math.Vector2
import org.loon.framework.android.game.physics.PolygonDef

internal fun Body.getAddr() = this.addr
internal fun Body.getJoints() = this.joints
internal fun Body.getLinVelLoc() = this.linVelLoc
internal fun Body.getLinVelWorld() = this.linVelWorld
internal fun Body.getLocalPoint2() = this.localPoint2
internal fun Body.getLocalVector() = this.localVector
internal fun Body.setJoints(value: ArrayList<JointEdge?>) { this.joints = value }
internal fun BodyDef.getActive() = this.active
internal fun BodyDef.getAllowSleep() = this.allowSleep
internal fun BodyDef.getAngle() = this.angle
internal fun BodyDef.getAngularDamping() = this.angularDamping
internal fun BodyDef.getAngularVelocity() = this.angularVelocity
internal fun BodyDef.getAwake() = this.awake
internal fun BodyDef.getBullet() = this.bullet
internal fun BodyDef.getFixedRotation() = this.fixedRotation
internal fun BodyDef.getInertiaScale() = this.inertiaScale
internal fun BodyDef.getLinearDamping() = this.linearDamping
internal fun BodyDef.getLinearVelocity() = this.linearVelocity
internal fun BodyDef.getPosition() = this.position
internal fun BodyDef.setActive(value: Boolean) { this.active = value }
internal fun BodyDef.setAllowSleep(value: Boolean) { this.allowSleep = value }
internal fun BodyDef.setAngle(value: Float) { this.angle = value }
internal fun BodyDef.setAngularDamping(value: Float) { this.angularDamping = value }
internal fun BodyDef.setAngularVelocity(value: Float) { this.angularVelocity = value }
internal fun BodyDef.setAwake(value: Boolean) { this.awake = value }
internal fun BodyDef.setBullet(value: Boolean) { this.bullet = value }
internal fun BodyDef.setFixedRotation(value: Boolean) { this.fixedRotation = value }
internal fun BodyDef.setInertiaScale(value: Float) { this.inertiaScale = value }
internal fun BodyDef.setLinearDamping(value: Float) { this.linearDamping = value }
internal fun ContactImpulse.getAddr() = this.addr
internal fun ContactImpulse.getNormalImpulses() = this.normalImpulses
internal fun ContactImpulse.getTangentImpulses() = this.tangentImpulses
internal fun ContactImpulse.getTmp() = this.tmp
internal fun ContactImpulse.getWorld() = this.world
internal fun ContactImpulse.setAddr(value: Long) { this.addr = value }
internal fun ContactImpulse.setTmp(value: FloatArray) { this.tmp = value }
internal fun Filter.getCategoryBits() = this.categoryBits
internal fun Filter.getGroupIndex() = this.groupIndex
internal fun Filter.getMaskBits() = this.maskBits
internal fun Filter.setCategoryBits(value: Short) { this.categoryBits = value }
internal fun Filter.setGroupIndex(value: Short) { this.groupIndex = value }
internal fun Filter.setMaskBits(value: Short) { this.maskBits = value }
internal fun FixtureDef.getDensity() = this.density
internal fun FixtureDef.getFilter() = this.filter
internal fun FixtureDef.getFriction() = this.friction
internal fun FixtureDef.getRestitution() = this.restitution
internal fun FixtureDef.getShape() = this.shape
internal fun FixtureDef.isSensor() = this.isSensor
internal fun FixtureDef.setDensity(value: Float) { this.density = value }
internal fun FixtureDef.setFriction(value: Float) { this.friction = value }
internal fun FixtureDef.setRestitution(value: Float) { this.restitution = value }
internal fun FixtureDef.setSensor(value: Boolean) { this.isSensor = value }
internal fun JointDef.getBodyA() = this.bodyA
internal fun JointDef.getBodyB() = this.bodyB
internal fun JointDef.getCollideConnected() = this.collideConnected
internal fun JointDef.setBodyA(value: Body?) { this.bodyA = value }
internal fun JointDef.setBodyB(value: Body?) { this.bodyB = value }
internal fun JointDef.setCollideConnected(value: Boolean) { this.collideConnected = value }
internal fun Manifold.ManifoldPoint.getContactID() = this.contactID
internal fun Manifold.ManifoldPoint.getLocalPoint() = this.localPoint
internal fun Manifold.ManifoldPoint.getNormalImpulse() = this.normalImpulse
internal fun Manifold.ManifoldPoint.getTangentImpulse() = this.tangentImpulse
internal fun Manifold.ManifoldPoint.setContactID(value: Int) { this.contactID = value }
internal fun Manifold.ManifoldPoint.setNormalImpulse(value: Float) { this.normalImpulse = value }
internal fun Manifold.ManifoldPoint.setTangentImpulse(value: Float) { this.tangentImpulse = value }
internal fun Manifold.getAddr() = this.addr
internal fun Manifold.getLocalNormal() = this.localNormal
internal fun Manifold.getLocalPoint() = this.localPoint
internal fun Manifold.getPoints() = this.points
internal fun Manifold.getTmpFloat() = this.tmpFloat
internal fun Manifold.getTmpInt() = this.tmpInt
internal fun Manifold.getWorld() = this.world
internal fun Manifold.setAddr(value: Long) { this.addr = value }
internal fun MassData.getCenter() = this.center
internal fun MassData.getI() = this.I
internal fun MassData.getMass() = this.mass
internal fun MassData.setI(value: Float) { this.I = value }
internal fun MassData.setMass(value: Float) { this.mass = value }
internal fun Shape.getAddr() = this.addr
internal fun Shape.setAddr(value: Long) { this.addr = value }
internal fun World.getBodies() = this.bodies
internal fun World.getFixtures() = this.fixtures
internal fun World.getGravity() = this.gravity
internal fun World.getTmpGravity() = this.tmpGravity
internal fun WorldManifold.getNormal() = this.normal
internal fun WorldManifold.getNumContactPoints() = this.numContactPoints
internal fun WorldManifold.getPoints() = this.points
internal fun WorldManifold.setNumContactPoints(value: Int) { this.numContactPoints = value }
